# Generated by Django 6.1 on 2026-08-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('skill', models.CharField(choices=[('VOCAB', 'Technical Vocabulary'), ('GRAMMAR', 'Grammar in Engineering Context'), ('READING', 'Technical Reading')], max_length=20)),
                ('aerospace_domain', models.CharField(choices=[('AERO', 'Aerodynamics'), ('FLIGHT', 'Flight Dynamics & Control'), ('PROP', 'Propulsion')], max_length=20)),
                ('difficulty', models.CharField(choices=[('BASIC', 'Basic'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BASIC', max_length=20)),
                ('explanation', models.TextField(blank=True)),
            ],
        ),
    ]
