# Generated by Django 6.1 on 2026-08-13 18:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='question',
            name='options_language',
            field=models.CharField(choices=[('EN', 'English'), ('FA', 'Persian')], default='EN', max_length=2),
        ),
        migrations.AddField(
            model_name='question',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='question_language',
            field=models.CharField(choices=[('EN', 'English'), ('FA', 'Persian')], default='EN', max_length=2),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SINGLE_MCQ', 'Single-answer MCQ')], default='SINGLE_MCQ', max_length=30),
        ),
        migrations.AddField(
            model_name='question',
            name='source_reference',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='question',
            name='source_type',
            field=models.CharField(choices=[('MANUAL', 'Teacher / Human Authored'), ('SEED', 'Demo Seed Data'), ('CORPUS', 'Corpus-derived'), ('IMPORTED', 'Imported'), ('AI', 'AI Generated')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('DEMO', 'Demo'), ('RETIRED', 'Retired')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='question',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='visibility',
            field=models.CharField(choices=[('PRIVATE', 'Teacher Private'), ('PRACTICE_EXAM', 'Practice + Exam'), ('EXAM_ONLY', 'Exam Only'), ('SHARED', 'Shared Teacher Bank'), ('AEROESP_BANK', 'AeroESP Bank')], default='PRIVATE', max_length=30),
        ),
    ]
