# Generated by Django 6.1 on 2026-08-13 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_question_created_at_question_options_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AerospaceDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='domain_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='assessment.aerospacedomain'),
        ),
        migrations.CreateModel(
            name='AerospaceTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='assessment.aerospacedomain')),
            ],
            options={
                'ordering': ('domain__order', 'order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='topic_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='assessment.aerospacetopic'),
        ),
        migrations.AddConstraint(
            model_name='aerospacetopic',
            constraint=models.UniqueConstraint(fields=('domain', 'code'), name='unique_topic_code_per_domain'),
        ),
    ]
