# Generated by Django 6.1 on 2026-08-13 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_aerospacedomain_question_domain_ref_aerospacetopic_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aerospacetopic',
            name='approval_status',
            field=models.CharField(choices=[('CORE', 'Core AeroESP Topic'), ('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='CORE', max_length=20),
        ),
        migrations.AddField(
            model_name='aerospacetopic',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_aerospace_topics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aerospacetopic',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='assessment.aerospacetopic'),
        ),
        migrations.AlterField(
            model_name='question',
            name='aerospace_domain',
            field=models.CharField(choices=[('GENERAL', 'General Aerospace & Fundamentals'), ('AERO', 'Aerodynamics & Fluid Mechanics'), ('FLIGHT', 'Flight Mechanics, Dynamics & Control'), ('PROP', 'Propulsion & Power Systems'), ('STRUCT', 'Structures & Materials'), ('DESIGN', 'Aircraft Design & Performance'), ('AVIONICS', 'Avionics, Navigation & Sensors'), ('SPACE', 'Space Engineering & Astronautics'), ('UAV', 'UAV, Robotics & Autonomous Systems'), ('SYSTEMS', 'Systems Engineering, Safety & Reliability'), ('MAINT', 'Manufacturing, Maintenance & Airworthiness'), ('METHODS', 'Experimental, Computational & Data Methods')], max_length=20),
        ),
    ]
