# Generated by Django 6.1 on 2026-08-13 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_aerospacetopic_approval_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aerospacetopic',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aerospacetopic',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aerospacetopic',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_aerospace_topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
