# Generated by Django 6.1 on 2026-08-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_aerospacetopic_review_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='track',
            field=models.CharField(choices=[('GENERAL_ENGLISH', 'General English / IELTS'), ('AEROSPACE_ESP', 'Aerospace English / ESP')], default='AEROSPACE_ESP', max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='aerospace_domain',
            field=models.CharField(blank=True, choices=[('GENERAL', 'General Aerospace & Fundamentals'), ('AERO', 'Aerodynamics & Fluid Mechanics'), ('FLIGHT', 'Flight Mechanics, Dynamics & Control'), ('PROP', 'Propulsion & Power Systems'), ('STRUCT', 'Structures & Materials'), ('DESIGN', 'Aircraft Design & Performance'), ('AVIONICS', 'Avionics, Navigation & Sensors'), ('SPACE', 'Space Engineering & Astronautics'), ('UAV', 'UAV, Robotics & Autonomous Systems'), ('SYSTEMS', 'Systems Engineering, Safety & Reliability'), ('MAINT', 'Manufacturing, Maintenance & Airworthiness'), ('METHODS', 'Experimental, Computational & Data Methods')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='skill',
            field=models.CharField(choices=[('VOCAB', 'Vocabulary'), ('GRAMMAR', 'Grammar'), ('READING', 'Reading'), ('LISTENING', 'Listening'), ('WRITING', 'Writing'), ('SPEAKING', 'Speaking')], max_length=20),
        ),
    ]
