# Generated by Django 6.1 on 2026-08-20 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0006_question_track_alter_question_aerospace_domain_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerInsightSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('GENERAL', 'General English'), ('AEROSPACE', 'Aerospace English'), ('OVERALL', 'Overall')], default='OVERALL', max_length=20)),
                ('risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('risk_band', models.CharField(blank=True, default='', max_length=20)),
                ('summary', models.TextField(blank=True, default='')),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('backend', models.CharField(default='EXPLAINABLE_BASELINE_V1', max_length=80)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insight_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['student', 'generated_at'], name='ai_insight_student_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuestionAISuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_track', models.CharField(blank=True, default='', max_length=40)),
                ('suggested_skill', models.CharField(blank=True, default='', max_length=40)),
                ('suggested_difficulty', models.CharField(blank=True, default='', max_length=40)),
                ('confidence', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('rationale', models.TextField(blank=True, default='')),
                ('backend', models.CharField(default='RULE_BASED_V1', max_length=80)),
                ('raw_output', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ai_question_suggestions', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='assessment.question')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ai_question_suggestions', to=settings.AUTH_USER_MODEL)),
                ('suggested_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_question_suggestions', to='assessment.aerospacedomain')),
                ('suggested_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_question_suggestions', to='assessment.aerospacetopic')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['question', 'status'], name='ai_question_status_idx')],
            },
        ),
    ]
