# Generated by Django 6.1 on 2026-08-25 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_question_track_alter_question_aerospace_domain_and_more'),
        ('intelligence', '0002_generatedquestiondraft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInteractionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('GENERATION_SUCCESS', 'Question Generation Success'), ('GENERATION_FAILURE', 'Question Generation Failure'), ('DRAFT_EDITED', 'Generated Draft Edited'), ('DRAFT_ACCEPTED', 'Generated Draft Accepted'), ('DRAFT_REJECTED', 'Generated Draft Rejected'), ('QUESTION_ANALYSIS', 'Question Analysis'), ('LEARNER_INSIGHT', 'Learner Insight')], max_length=40)),
                ('provider', models.CharField(blank=True, default='', max_length=80)),
                ('model_name', models.CharField(blank=True, default='', max_length=120)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=80)),
                ('success', models.BooleanField(default=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('total_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, default='', max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_interaction_events', to=settings.AUTH_USER_MODEL)),
                ('draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interaction_events', to='intelligence.generatedquestiondraft')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_interaction_events', to='assessment.question')),
                ('subject_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_subject_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='ai_event_type_time_idx'), models.Index(fields=['actor', 'created_at'], name='ai_event_actor_time_idx')],
            },
        ),
    ]
