# Generated by Django 6.1 on 2026-08-25 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0003_aiinteractionevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIQualitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('decision', models.CharField(blank=True, max_length=100)),
                ('quality_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_snapshots', to='intelligence.generatedquestiondraft')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_snapshots', to='intelligence.aiinteractionevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
