# Generated by Django 6.1 on 2026-08-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0005_aipromptversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
