# Generated by Django 6.1 on 2026-08-26 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0006_aiexperiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIExperimentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100)),
                ('generations', models.PositiveIntegerField(default=0)),
                ('quality_score', models.FloatField(default=0)),
                ('acceptance_rate', models.FloatField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='intelligence.aiexperiment')),
            ],
        ),
    ]
