# Generated by Django 6.1 on 2026-08-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0007_aiexperimentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiexperimentresult',
            name='recommendation',
            field=models.CharField(default='', max_length=50),
        ),
    ]
