# Generated by Django 6.1 on 2026-08-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0009_aiexperiment_dataset_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiexperimentresult',
            name='ai_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='aiexperimentresult',
            name='dataset_version',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='aiexperimentresult',
            name='human_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='aiexperimentresult',
            name='model_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='aiexperimentresult',
            name='prompt_version',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
