# Generated by Django 6.1 on 2026-08-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0010_aiexperimentresult_ai_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIEvaluationDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('domain', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
