# Generated by Django 6.1 on 2026-08-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0012_aiexperiment_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIEvaluationProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('metrics', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
