# Generated by Django 6.1 on 2026-08-26 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0013_aievaluationprotocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiexperiment',
            name='protocol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiments', to='intelligence.aievaluationprotocol'),
        ),
    ]
