# Generated by Django 6.1 on 2026-08-27 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0015_aiexperiment_experiment_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(choices=[('BASELINE_V1', 'Baseline Free'), ('OPENAI_RESPONSES_V1', 'OpenAI'), ('DEEPSEEK_V1', 'DeepSeek'), ('GEMINI_V1', 'Gemini')], default='BASELINE_V1', max_length=50)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('api_key', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('monthly_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_provider_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'provider_name')},
            },
        ),
    ]
