# Generated by Django 5.2.17 on 2026-09-08 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0017_alter_aiproviderconfiguration_api_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aievaluationdataset',
            options={'verbose_name': 'AI evaluation dataset', 'verbose_name_plural': 'AI evaluation datasets'},
        ),
        migrations.AlterModelOptions(
            name='aievaluationprotocol',
            options={'verbose_name': 'AI evaluation protocol', 'verbose_name_plural': 'AI evaluation protocols'},
        ),
        migrations.AlterModelOptions(
            name='aiexperiment',
            options={'verbose_name': 'AI experiment', 'verbose_name_plural': 'AI experiments'},
        ),
        migrations.AlterModelOptions(
            name='aiexperimentresult',
            options={'verbose_name': 'AI experiment result', 'verbose_name_plural': 'AI experiment results'},
        ),
        migrations.AlterModelOptions(
            name='aigenerationlog',
            options={'verbose_name': 'AI generation log', 'verbose_name_plural': 'AI generation logs'},
        ),
        migrations.AlterModelOptions(
            name='aiinteractionevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'AI interaction event', 'verbose_name_plural': 'AI interaction events'},
        ),
        migrations.AlterModelOptions(
            name='aipromptversion',
            options={'ordering': ['-created_at'], 'verbose_name': 'AI prompt version', 'verbose_name_plural': 'AI prompt versions'},
        ),
        migrations.AlterModelOptions(
            name='aiproviderconfiguration',
            options={'verbose_name': 'AI provider configuration', 'verbose_name_plural': 'AI provider configurations'},
        ),
        migrations.AlterModelOptions(
            name='aiqualitysnapshot',
            options={'ordering': ['-created_at'], 'verbose_name': 'AI quality snapshot', 'verbose_name_plural': 'AI quality snapshots'},
        ),
        migrations.AlterModelOptions(
            name='questionaisuggestion',
            options={'ordering': ['-created_at'], 'verbose_name': 'question AI suggestion', 'verbose_name_plural': 'question AI suggestions'},
        ),
    ]
