# Generated by Django 6.1 on 2026-08-31 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_selected_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='selected_role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher')], default='STUDENT', max_length=10),
        ),
    ]
