# Generated by Django 6.1 on 2026-09-05 10:10

from django.db import migrations, models


def blank_emails_to_null(apps, schema_editor):
    """
    Idempotent safety net for databases where the earlier migration
    had already run: keep "no email" stored as NULL, never as "".
    """

    CustomUser = apps.get_model(
        "accounts",
        "CustomUser",
    )

    CustomUser.objects.filter(
        email="",
    ).update(
        email=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_selected_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverificationcode',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.RunPython(
            blank_emails_to_null,
            migrations.RunPython.noop,
        ),
    ]
