# Generated by Django 6.1 on 2026-09-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_selected_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverificationcode',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
