# Generated by Django 5.2.17 on 2026-09-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_captchachallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='captchachallenge',
            name='image_dark',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
