# Generated by Django 5.2.17 on 2026-09-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_terms_accepted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('EVERYONE', 'Everyone'), ('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('EXPERT_REVIEWER', 'Expert Reviewer')], default='EVERYONE', help_text="Who this guide is for. It appears on the public list for everyone, and is what the in-app Help icon matches against the signed-in user's role.", max_length=20)),
                ('slug', models.SlugField(help_text="Used in the guide's URL. 'expert-reviewer-getting-started' is used automatically by the /expert-review/getting-started/ link if present.", max_length=140, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, help_text='Short teaser shown next to the link on the list.', max_length=300)),
                ('body', models.TextField(blank=True, help_text='Plain text is fine - line breaks are preserved. Leave empty for a file-only guide.')),
                ('attachment', models.FileField(blank=True, help_text='Optional: a PDF or document to offer for download.', null=True, upload_to='guides/')),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first within the same audience.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('audience', 'order', 'title'),
            },
        ),
    ]
