# Generated by Django 5.2.17 on 2026-09-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_helpguide'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='color_palette',
            field=models.CharField(choices=[('skyline', 'Skyline'), ('copper', 'Copper'), ('indigo', 'Indigo'), ('verdigris', 'Verdigris'), ('slate', 'Slate')], default='skyline', max_length=20),
        ),
    ]
