# Generated by Django 5.2.17 on 2026-09-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_color_palette'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.CharField(choices=[('INITIAL', 'Initial'), ('delta', 'Delta wing'), ('orbit', 'Orbit'), ('vector', 'Ascent'), ('turbine', 'Turbine'), ('radar', 'Radar'), ('contrail', 'Contrail'), ('lattice', 'Lattice'), ('polaris', 'Polaris')], default='INITIAL', max_length=20),
        ),
    ]
