# Generated by Django 6.1 on 2026-08-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_examattempt_max_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='flag_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='flagged_for_review',
            field=models.BooleanField(default=False),
        ),
    ]
