# Generated by Django 6.1 on 2026-08-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_studentanswer_flag_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examevent',
            name='event_type',
            field=models.CharField(choices=[('ATTEMPT_STARTED', 'Attempt Started'), ('QUESTION_VIEWED', 'Question Viewed'), ('ANSWER_SAVED', 'Answer Saved'), ('ANSWER_CHANGED', 'Answer Changed'), ('PAGE_FOCUS', 'Page Focus'), ('PAGE_BLUR', 'Page Blur'), ('SUBMITTED', 'Submitted'), ('AUTO_SUBMITTED', 'Auto Submitted'), ('RECONNECTED', 'Reconnected'), ('SECURE_MODE_STARTED', 'Secure Mode Started'), ('SECURITY_VIOLATION', 'Security Violation')], max_length=30),
        ),
    ]
