# Generated by Django 6.1 on 2026-08-23 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_examevent_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='integrity_decision',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('CLEAR', 'No Action Required'), ('REVIEW', 'Further Review Required'), ('CONFIRMED', 'Integrity Violation Confirmed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='integrity_review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='integrity_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='integrity_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_exam_integrity_attempts', to=settings.AUTH_USER_MODEL),
        ),
    ]
