# Generated by Django 6.1 on 2026-08-30 21:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_id', models.CharField(max_length=50, unique=True)),
                ('source_id', models.CharField(max_length=20, unique=True)),
                ('domain', models.CharField(max_length=150)),
                ('topic', models.CharField(max_length=255)),
                ('protocol', models.CharField(max_length=50)),
                ('target_cefr', models.CharField(default='B2', max_length=10)),
                ('target_cognitive_level', models.CharField(default='UNDERSTAND', max_length=30)),
                ('source_material', models.TextField(blank=True)),
                ('is_confirmatory', models.BooleanField(default=True)),
                ('is_frozen', models.BooleanField(default=True, help_text='Frozen research experiments should not be silently modified.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['source_id'],
            },
        ),
        migrations.CreateModel(
            name='ExpertReviewerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(choices=[('AEROSPACE', 'Aerospace Engineering'), ('ESP', 'ESP / Language Assessment'), ('BOTH', 'Aerospace + ESP'), ('OTHER', 'Other')], max_length=20)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('is_active_reviewer', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expert_reviewer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=80, unique=True)),
                ('provider', models.CharField(max_length=100)),
                ('displayed_model', models.CharField(blank=True, max_length=150)),
                ('condition', models.CharField(blank=True, max_length=255)),
                ('raw_output_format', models.CharField(default='JSON', max_length=100)),
                ('json_valid', models.BooleanField(default=True)),
                ('schema_compliant', models.BooleanField(default=True)),
                ('item_count_compliant', models.BooleanField(default=True)),
                ('skill_sequence_compliant', models.BooleanField(default=True)),
                ('answer_position_compliant', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='research_review.researchexperiment')),
            ],
            options={
                'ordering': ['experiment__source_id', 'run_id'],
            },
        ),
        migrations.CreateModel(
            name='ResearchQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blind_id', models.CharField(max_length=30, unique=True)),
                ('item_number', models.PositiveSmallIntegerField()),
                ('skill', models.CharField(choices=[('main_idea', 'Main Idea'), ('specific_information', 'Specific Information'), ('inference', 'Inference'), ('vocabulary_in_context', 'Vocabulary in Context'), ('technical_comprehension', 'Technical Comprehension'), ('cause_and_effect', 'Cause and Effect'), ('applied_understanding', 'Applied Understanding')], max_length=40)),
                ('stem', models.TextField()),
                ('option_a', models.TextField()),
                ('option_b', models.TextField()),
                ('option_c', models.TextField()),
                ('option_d', models.TextField()),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('explanation', models.TextField(blank=True)),
                ('source_evidence', models.TextField(blank=True)),
                ('raw_preserved', models.BooleanField(default=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('promoted_to_operational_bank', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='research_review.researchrun')),
            ],
            options={
                'ordering': ['run__experiment__source_id', 'run__run_id', 'item_number'],
            },
        ),
        migrations.CreateModel(
            name='ReviewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('LOCKED', 'Locked')], default='NOT_STARTED', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='research_review.researchquestion')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='research_review.expertreviewerprofile')),
            ],
            options={
                'ordering': ['reviewer', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='ExpertReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_correctness', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('linguistic_accuracy', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('clarity_answerability', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('source_fidelity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('distractor_quality', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('cefr_alignment', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('difficulty_alignment', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('pedagogical_value', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('expert_cefr', models.CharField(choices=[('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=10)),
                ('expert_cognitive_level', models.CharField(choices=[('REMEMBER', 'Remember'), ('UNDERSTAND', 'Understand'), ('APPLY', 'Apply'), ('ANALYZE', 'Analyze')], max_length=20)),
                ('keyed_answer_correct', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('ambiguous', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('multiple_correct_answers', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('overall_decision', models.CharField(choices=[('ACCEPT', 'Accept'), ('MINOR_EDIT', 'Minor Edit'), ('MAJOR_EDIT', 'Major Edit'), ('REJECT', 'Reject')], max_length=20)),
                ('error_codes', models.CharField(blank=True, max_length=255)),
                ('comments', models.TextField(blank=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='research_review.reviewassignment')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='research_review_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='research_review.expertreview')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='researchquestion',
            constraint=models.UniqueConstraint(fields=('run', 'item_number'), name='unique_research_item_per_run'),
        ),
        migrations.AddConstraint(
            model_name='reviewassignment',
            constraint=models.UniqueConstraint(fields=('reviewer', 'question'), name='unique_reviewer_question_assignment'),
        ),
    ]
