# Generated by Django 6.1 on 2026-08-30 23:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertreview',
            name='ambiguous',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='expertreview',
            name='cefr_alignment',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='expertreview',
            name='clarity_answerability',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='expertreview',
            name='difficulty_alignment',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='expertreview',
            name='distractor_quality',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='expertreview',
            name='expert_cefr',
            field=models.CharField(blank=True, choices=[('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='expertreview',
            name='expert_cognitive_level',
            field=models.CharField(blank=True, choices=[('REMEMBER', 'Remember'), ('UNDERSTAND', 'Understand'), ('APPLY', 'Apply'), ('ANALYZE', 'Analyze')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='expertreview',
            name='keyed_answer_correct',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='expertreview',
            name='linguistic_accuracy',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='expertreview',
            name='multiple_correct_answers',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='expertreview',
            name='overall_decision',
            field=models.CharField(blank=True, choices=[('ACCEPT', 'Accept'), ('MINOR_EDIT', 'Minor Edit'), ('MAJOR_EDIT', 'Major Edit'), ('REJECT', 'Reject')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='expertreview',
            name='pedagogical_value',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='expertreview',
            name='source_fidelity',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='expertreview',
            name='technical_correctness',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
