# Generated by Django 5.2.17 on 2026-09-07 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_review', '0002_alter_expertreview_ambiguous_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertreview',
            name='construct_relevance',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How relevant is this item to the construct of English language proficiency in the aerospace engineering domain? 1=Not relevant, 2=Somewhat relevant (major revision), 3=Relevant (minor revision), 4=Highly relevant', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
