# Generated by Django 5.2.17 on 2026-09-07 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_review', '0003_expertreview_construct_relevance'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertreview',
            name='reviewer_confidence',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional: how confident are you in this assessment? 1=Not confident, 5=Very confident.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='expertreview',
            name='time_spent_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
