# Generated by Django 5.2.17 on 2026-09-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_review', '0004_expertreview_reviewer_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchquestion',
            name='question_provenance',
            field=models.CharField(choices=[('AI_GENERATED', 'AI Generated'), ('HUMAN_WRITTEN', 'Human Written'), ('EXISTING_SOURCE', 'Existing Source')], default='AI_GENERATED', max_length=20),
        ),
    ]
