# Generated by Django 5.2.17 on 2026-09-07 11:07
# Hand-edited: makemigrations paired this AddField with a RemoveField
# of the old error_codes CharField, which would have destroyed every
# existing value before the data migration (0007) gets a chance to
# copy it across. The old field is removed in 0008 instead, once 0007
# has run.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_review', '0005_researchquestion_question_provenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertreview',
            name='error_codes_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
