# Generated by Django 5.2.17 on 2026-09-07 11:19
# Hand-edited: the autodetected single AddField(unique=True) is only
# safe when at most one ExpertReviewerProfile row already exists - two
# or more rows would all default to reviewer_code="" and collide on
# the unique index the instant this ran against a database that
# already has reviewers in it. Split into add (no constraint yet) ->
# backfill -> add the constraint once every row actually has a value.

from django.db import migrations, models


def backfill_reviewer_codes(apps, schema_editor):

    ExpertReviewerProfile = apps.get_model(
        "research_review",
        "ExpertReviewerProfile",
    )

    profiles = ExpertReviewerProfile.objects.order_by(
        "created_at",
        "pk",
    )

    for number, profile in enumerate(profiles, start=1):

        profile.reviewer_code = f"R{number:02d}"
        profile.save(
            update_fields=["reviewer_code"],
        )


def clear_reviewer_codes(apps, schema_editor):

    ExpertReviewerProfile = apps.get_model(
        "research_review",
        "ExpertReviewerProfile",
    )

    ExpertReviewerProfile.objects.update(
        reviewer_code="",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('research_review', '0008_error_codes_json_to_error_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertreviewerprofile',
            name='reviewer_code',
            field=models.CharField(
                blank=True,
                default="",
                max_length=10,
            ),
        ),
        migrations.RunPython(
            backfill_reviewer_codes,
            clear_reviewer_codes,
        ),
        migrations.AlterField(
            model_name='expertreviewerprofile',
            name='reviewer_code',
            field=models.CharField(
                blank=True,
                max_length=10,
                unique=True,
            ),
        ),
    ]
