"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# =========================================================
# Environment / Security
# =========================================================

DJANGO_ENV = os.getenv(
    "DJANGO_ENV",
    "development",
).strip().lower()

IS_PRODUCTION = (
    DJANGO_ENV == "production"
)

SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-aeroesp-local-development-only",
)

DEBUG = (
    os.getenv(
        "DJANGO_DEBUG",
        "0" if IS_PRODUCTION else "1",
    )
    .strip()
    .lower()
    in {
        "1",
        "true",
        "yes",
        "on",
    }
)

_default_hosts = (
    "127.0.0.1,localhost"
    if not IS_PRODUCTION
    else ""
)

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "DJANGO_ALLOWED_HOSTS",
        _default_hosts,
    ).split(",")
    if host.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "DJANGO_CSRF_TRUSTED_ORIGINS",
        "",
    ).split(",")
    if origin.strip()
]


# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "accounts.apps.AccountsConfig",
    "assessment",
    "exams.apps.ExamsConfig",
    "intelligence",
    "learning.apps.LearningConfig",
    "research_review",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "templates",
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DB_BACKEND = os.environ.get(
    "AEROESP_DB_BACKEND",
    "postgresql",
).lower()

if DB_BACKEND == "postgresql":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("AEROESP_DB_NAME", "aeroesp"),
            "USER": os.environ.get("AEROESP_DB_USER", "aeroesp_user"),
            "PASSWORD": os.environ["AEROESP_DB_PASSWORD"],
            "HOST": os.environ.get("AEROESP_DB_HOST", "localhost"),
            "PORT": os.environ.get("AEROESP_DB_PORT", "5432"),
        }
    }

elif DB_BACKEND == "sqlite":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

else:
    raise ValueError(
        f"Unsupported AEROESP_DB_BACKEND: {DB_BACKEND}"
    )

# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = (
    BASE_DIR
    / "staticfiles"
)

STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# =========================================================
# Email
# =========================================================

EMAIL_BACKEND = os.getenv(
    "DJANGO_EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)

EMAIL_HOST = os.getenv(
    "DJANGO_EMAIL_HOST",
    "",
)

EMAIL_PORT = int(
    os.getenv(
        "DJANGO_EMAIL_PORT",
        "587",
    )
)

EMAIL_USE_TLS = (
    os.getenv(
        "DJANGO_EMAIL_USE_TLS",
        "1",
    )
    == "1"
)

EMAIL_USE_SSL = (
    os.getenv(
        "DJANGO_EMAIL_USE_SSL",
        "0",
    )
    == "1"
)

EMAIL_HOST_USER = os.getenv(
    "DJANGO_EMAIL_HOST_USER",
    "",
)

EMAIL_HOST_PASSWORD = os.getenv(
    "DJANGO_EMAIL_HOST_PASSWORD",
    "",
)

DEFAULT_FROM_EMAIL = os.getenv(
    "DJANGO_DEFAULT_FROM_EMAIL",
    "AeroESP <noreply@example.com>",
)

SERVER_EMAIL = os.getenv(
    "DJANGO_SERVER_EMAIL",
    DEFAULT_FROM_EMAIL,
)

EMAIL_TIMEOUT = int(
    os.getenv(
        "DJANGO_EMAIL_TIMEOUT",
        "20",
    )
)

AUTH_USER_MODEL = "accounts.CustomUser"

LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "accounts:role_redirect"
LOGOUT_REDIRECT_URL = "accounts:login"


# =========================================================
# AeroESP AI configuration
# =========================================================

AEROESP_AI_PROVIDER = os.getenv(
    "AEROESP_AI_PROVIDER",
    "BASELINE_V1",
)

AEROESP_OPENAI_MODEL = os.getenv(
    "AEROESP_OPENAI_MODEL",
    "gpt-5.6-luna",
)

AEROESP_OPENAI_TIMEOUT = int(
    os.getenv(
        "AEROESP_OPENAI_TIMEOUT",
        "45",
    )
)

AEROESP_SECRET_KEY = os.getenv(
    "AEROESP_SECRET_KEY",
    "",
).strip()


# =========================================================
# Production Security
# =========================================================

if IS_PRODUCTION:

    if not SECRET_KEY:
        raise RuntimeError(
            "DJANGO_SECRET_KEY is required "
            "in production."
        )

    if not AEROESP_SECRET_KEY:
        raise RuntimeError(
            "AEROESP_SECRET_KEY is required "
            "in production."
        )

    SECURE_SSL_REDIRECT = True

    SESSION_COOKIE_SECURE = True

    CSRF_COOKIE_SECURE = True

    SESSION_COOKIE_HTTPONLY = True

    CSRF_COOKIE_HTTPONLY = False

    SECURE_CONTENT_TYPE_NOSNIFF = True

    X_FRAME_OPTIONS = "DENY"

    SECURE_REFERRER_POLICY = (
        "strict-origin-when-cross-origin"
    )

    SECURE_PROXY_SSL_HEADER = (
        "HTTP_X_FORWARDED_PROTO",
        "https",
    )

    USE_X_FORWARDED_HOST = True

    SECURE_HSTS_SECONDS = int(
        os.getenv(
            "DJANGO_SECURE_HSTS_SECONDS",
            "3600",
        )
    )

    SECURE_HSTS_INCLUDE_SUBDOMAINS = (
        os.getenv(
            "DJANGO_HSTS_INCLUDE_SUBDOMAINS",
            "0",
        )
        == "1"
    )

    SECURE_HSTS_PRELOAD = (
        os.getenv(
            "DJANGO_HSTS_PRELOAD",
            "0",
        )
        == "1"
    )

else:

    SECURE_SSL_REDIRECT = False

    SESSION_COOKIE_SECURE = False

    CSRF_COOKIE_SECURE = False

    SECURE_HSTS_SECONDS = 0


# =========================================================
# Logging
# =========================================================

LOG_LEVEL = os.getenv(
    "DJANGO_LOG_LEVEL",
    "INFO",
).upper()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": (
                "{levelname} "
                "{asctime} "
                "{name} "
                "{message}"
            ),
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": (
                "logging.StreamHandler"
            ),
            "formatter": (
                "standard"
            ),
        },
    },
    "root": {
        "handlers": [
            "console",
        ],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": [
                "console",
            ],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "learning": {
            "handlers": [
                "console",
            ],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "intelligence": {
            "handlers": [
                "console",
            ],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}