"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
from urllib.parse import unquote, urlparse
import os
import sys

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Which .env file to load. Defaults to ".env"; set AEROESP_ENV_FILE to
# point at another one for a single command, e.g. to run a management
# command against the production database from a local machine:
#
#   AEROESP_ENV_FILE=.env.production.local python manage.py shell
#
# Nothing on disk is modified, so the next command without the variable
# is back on the normal local configuration.
ENV_FILE = Path(
    os.environ.get(
        "AEROESP_ENV_FILE",
        ".env",
    )
)

if not ENV_FILE.is_absolute():
    ENV_FILE = BASE_DIR / ENV_FILE

if not ENV_FILE.exists() and "AEROESP_ENV_FILE" in os.environ:
    raise RuntimeError(
        f"AEROESP_ENV_FILE points at {ENV_FILE}, which does not exist."
    )

load_dotenv(ENV_FILE)


# =========================================================
# Environment / Security
# =========================================================

DJANGO_ENV = os.getenv(
    "DJANGO_ENV",
    "development",
).strip().lower()

IS_PRODUCTION = (
    DJANGO_ENV == "production"
)

SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-aeroesp-local-development-only",
)

DEBUG = (
    os.getenv(
        "DJANGO_DEBUG",
        "0" if IS_PRODUCTION else "1",
    )
    .strip()
    .lower()
    in {
        "1",
        "true",
        "yes",
        "on",
    }
)

_default_hosts = (
    "127.0.0.1,localhost"
    if not IS_PRODUCTION
    else ""
)

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "DJANGO_ALLOWED_HOSTS",
        _default_hosts,
    ).split(",")
    if host.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "DJANGO_CSRF_TRUSTED_ORIGINS",
        "",
    ).split(",")
    if origin.strip()
]


# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "accounts.apps.AccountsConfig",
    "assessment",
    "exams.apps.ExamsConfig",
    "intelligence",
    "learning.apps.LearningConfig",
    "research_review",

    "axes",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "templates",
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DB_BACKEND = os.environ.get(
    "AEROESP_DB_BACKEND",
    "postgresql",
).lower()


def _database_from_url(url):
    """
    Split a postgres://user:password@host:port/name URL into the parts
    Django wants.

    Render (and most hosts) hand out a single connection URL rather
    than separate fields, so accepting one avoids transcribing five
    values by hand and getting one of them subtly wrong.
    """

    parts = urlparse(url)

    if parts.scheme not in {"postgres", "postgresql"}:
        raise ValueError(
            "DATABASE_URL must start with postgres:// or postgresql://"
        )

    return {
        "NAME": parts.path.lstrip("/"),
        "USER": unquote(parts.username or ""),
        "PASSWORD": unquote(parts.password or ""),
        "HOST": parts.hostname or "",
        "PORT": str(parts.port or "5432"),
    }


if DB_BACKEND == "postgresql":

    database_url = os.environ.get(
        "DATABASE_URL",
        "",
    ).strip()

    if database_url:
        _config = _database_from_url(database_url)

    else:
        _config = {
            "NAME": os.environ.get("AEROESP_DB_NAME", "aeroesp"),
            "USER": os.environ.get("AEROESP_DB_USER", "aeroesp_user"),
            "PASSWORD": os.environ["AEROESP_DB_PASSWORD"],
            "HOST": os.environ.get("AEROESP_DB_HOST", "localhost"),
            "PORT": os.environ.get("AEROESP_DB_PORT", "5432"),
        }

    # Managed Postgres (Render, Neon, Supabase, ...) refuses plain-text
    # connections from outside its own network. Local sockets do not
    # offer TLS at all, so only require it for remote hosts.
    _is_local_db = _config["HOST"] in {
        "",
        "localhost",
        "127.0.0.1",
        "::1",
    }

    _sslmode = os.environ.get(
        "AEROESP_DB_SSLMODE",
        "prefer" if _is_local_db else "require",
    ).strip()

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "OPTIONS": {
                "sslmode": _sslmode,
            },
            "CONN_MAX_AGE": int(
                os.environ.get(
                    "AEROESP_DB_CONN_MAX_AGE",
                    "0" if _is_local_db else "60",
                )
            ),
            **_config,
        }
    }

    # Working against a remote database by accident is the expensive
    # mistake here, so say out loud which one is in use.
    if not _is_local_db and len(sys.argv) > 1:
        sys.stderr.write(
            f"\n*** REMOTE DATABASE: {_config['HOST']} "
            f"(db: {_config['NAME']}, env: {ENV_FILE.name}) ***\n\n"
        )

elif DB_BACKEND == "sqlite":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

else:
    raise ValueError(
        f"Unsupported AEROESP_DB_BACKEND: {DB_BACKEND}"
    )

# Primary key type for models that do not declare one.
#
# Stated explicitly rather than inherited: Django 6.0 changed the
# built-in default from AutoField to BigAutoField, so leaving it
# implicit makes the same models resolve differently on 5.2 and 6.x.
# Every existing migration was generated with BigAutoField, which is
# what the database actually holds.
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [

    {
        "NAME":
        "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },

    {
        "NAME":
        "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 10,
        }
    },

    {
        "NAME":
        "django.contrib.auth.password_validation.CommonPasswordValidator",
    },

    {
        "NAME":
        "django.contrib.auth.password_validation.NumericPasswordValidator",
    },

]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = (
    BASE_DIR
    / "staticfiles"
)

STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# Media files (user uploads: profile images, learning attachments)
# https://docs.djangoproject.com/en/6.1/topics/files/

MEDIA_URL = "/media/"
MEDIA_ROOT = (
    BASE_DIR
    / "media"
)


# WhiteNoise serves the collected static files in production.
# CompressedStaticFilesStorage (no manifest) is used on purpose:
# a missing file must not turn into a 500 on a live page.

STORAGES = {
    "default": {
        "BACKEND": (
            "django.core.files.storage."
            "FileSystemStorage"
        ),
    },
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage."
            "CompressedStaticFilesStorage"
        ),
    },
}

WHITENOISE_MAX_AGE = 31536000 if IS_PRODUCTION else 0


# =========================================================
# Email
# =========================================================


def _env(name, default=""):
    """
    Read an environment variable, treating a present-but-empty value
    the same as an absent one.

    Without this, a bare "DJANGO_EMAIL_BACKEND=" line in .env would
    override the default with an empty string and break sending.
    """

    value = os.getenv(name)

    if value is None:
        return default

    value = value.strip()

    return value if value else default


def _env_flag(name, default="0"):
    return _env(name, default).lower() in {
        "1",
        "true",
        "yes",
        "on",
    }


EMAIL_BACKEND = _env(
    "DJANGO_EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)

EMAIL_HOST = _env("DJANGO_EMAIL_HOST")

EMAIL_PORT = int(
    _env(
        "DJANGO_EMAIL_PORT",
        "587",
    )
)

EMAIL_USE_TLS = _env_flag(
    "DJANGO_EMAIL_USE_TLS",
    "1",
)

EMAIL_USE_SSL = _env_flag(
    "DJANGO_EMAIL_USE_SSL",
    "0",
)

EMAIL_HOST_USER = _env("DJANGO_EMAIL_HOST_USER")

# Gmail shows App Passwords grouped as "abcd efgh ijkl mnop" for
# readability, and they are routinely pasted with those spaces still
# in place. The password itself contains no whitespace, so stripping
# it here turns a confusing authentication failure into a working
# login. The value in .env is left exactly as the owner typed it.
EMAIL_HOST_PASSWORD = "".join(
    _env("DJANGO_EMAIL_HOST_PASSWORD").split()
)

DEFAULT_FROM_EMAIL = _env(
    "DJANGO_DEFAULT_FROM_EMAIL",
    # Fall back to the authenticated mailbox: Gmail rejects any
    # sender address other than the account that is signed in.
    EMAIL_HOST_USER or "AeroESP <noreply@example.com>",
)

SERVER_EMAIL = _env(
    "DJANGO_SERVER_EMAIL",
    DEFAULT_FROM_EMAIL,
)

EMAIL_TIMEOUT = int(
    _env(
        "DJANGO_EMAIL_TIMEOUT",
        "20",
    )
)

AUTH_USER_MODEL = "accounts.CustomUser"

# Authentication backends
# AxesStandaloneBackend must come first so that django-axes
# can block login attempts before they reach the model backend.
AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
]

LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "accounts:role_redirect"
LOGOUT_REDIRECT_URL = "accounts:login"


# =========================================================
# AeroESP AI configuration
# =========================================================

AEROESP_AI_PROVIDER = os.getenv(
    "AEROESP_AI_PROVIDER",
    "BASELINE_V1",
)

AEROESP_OPENAI_MODEL = os.getenv(
    "AEROESP_OPENAI_MODEL",
    "gpt-5.6-luna",
)

AEROESP_OPENAI_TIMEOUT = int(
    os.getenv(
        "AEROESP_OPENAI_TIMEOUT",
        "45",
    )
)

AEROESP_SECRET_KEY = os.getenv(
    "AEROESP_SECRET_KEY",
    "",
).strip()


# =========================================================
# Production Security
# =========================================================

if IS_PRODUCTION:

    if not SECRET_KEY:
        raise RuntimeError(
            "DJANGO_SECRET_KEY is required "
            "in production."
        )

    if not AEROESP_SECRET_KEY:
        raise RuntimeError(
            "AEROESP_SECRET_KEY is required "
            "in production."
        )

    SECURE_SSL_REDIRECT = True

    SESSION_COOKIE_SECURE = True

    CSRF_COOKIE_SECURE = True

    SESSION_COOKIE_HTTPONLY = True

    CSRF_COOKIE_HTTPONLY = False

    SECURE_CONTENT_TYPE_NOSNIFF = True

    X_FRAME_OPTIONS = "DENY"

    SECURE_REFERRER_POLICY = (
        "strict-origin-when-cross-origin"
    )

    SECURE_PROXY_SSL_HEADER = (
        "HTTP_X_FORWARDED_PROTO",
        "https",
    )

    USE_X_FORWARDED_HOST = True

    SECURE_HSTS_SECONDS = int(
        os.getenv(
            "DJANGO_SECURE_HSTS_SECONDS",
            "3600",
        )
    )

    SECURE_HSTS_INCLUDE_SUBDOMAINS = (
        os.getenv(
            "DJANGO_HSTS_INCLUDE_SUBDOMAINS",
            "0",
        )
        == "1"
    )

    SECURE_HSTS_PRELOAD = (
        os.getenv(
            "DJANGO_HSTS_PRELOAD",
            "0",
        )
        == "1"
    )

else:

    SECURE_SSL_REDIRECT = False

    SESSION_COOKIE_SECURE = False

    CSRF_COOKIE_SECURE = False

    SECURE_HSTS_SECONDS = 0


# =========================================================
# Logging
# =========================================================

LOG_LEVEL = os.getenv(
    "DJANGO_LOG_LEVEL",
    "INFO",
).upper()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": (
                "{levelname} "
                "{asctime} "
                "{name} "
                "{message}"
            ),
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": (
                "logging.StreamHandler"
            ),
            "formatter": (
                "standard"
            ),
        },
    },
    "root": {
        "handlers": [
            "console",
        ],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": [
                "console",
            ],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "accounts": {
            "handlers": [
                "console",
            ],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "learning": {
            "handlers": [
                "console",
            ],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "intelligence": {
            "handlers": [
                "console",
            ],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}


# =========================================================
# Axes (Brute force protection)
# =========================================================

AXES_FAILURE_LIMIT = 5

AXES_COOLOFF_TIME = 1

AXES_RESET_ON_SUCCESS = True

AXES_LOCKOUT_PARAMETERS = [
    ["username", "ip_address"],
]


# =========================================================
# Startup diagnostics
# =========================================================

# A production deployment whose mail backend cannot deliver looks
# perfectly healthy: registration returns 302 and no error is raised,
# but no user can ever finish signing up. Say so at boot, where the
# host's log will show it.

if IS_PRODUCTION and EMAIL_BACKEND.endswith(
    (
        "console.EmailBackend",
        "locmem.EmailBackend",
        "dummy.EmailBackend",
        "filebased.EmailBackend",
    )
):
    sys.stderr.write(
        "\n*** EMAIL NOT CONFIGURED: EMAIL_BACKEND is "
        f"{EMAIL_BACKEND}, which never delivers. Verification codes "
        "will not reach users. Set DJANGO_EMAIL_BACKEND to "
        "django.core.mail.backends.smtp.EmailBackend. ***\n\n"
    )