# Generated by Django 6.1 on 2026-08-19 18:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0005_aerospacetopic_review_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('title_fa', models.CharField(blank=True, max_length=150)),
                ('program_type', models.CharField(choices=[('IELTS', 'IELTS / General English'), ('AEROSPACE_ESP', 'Aerospace English / ESP')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LearningCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('title_fa', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(blank=True, choices=[('BEGINNER', 'Beginner'), ('ELEMENTARY', 'Elementary'), ('PRE_INTERMEDIATE', 'Pre-Intermediate'), ('INTERMEDIATE', 'Intermediate'), ('UPPER_INTERMEDIATE', 'Upper-Intermediate'), ('ADVANCED', 'Advanced'), ('IELTS_5', 'IELTS Band 5'), ('IELTS_55', 'IELTS Band 5.5'), ('IELTS_6', 'IELTS Band 6'), ('IELTS_65', 'IELTS Band 6.5'), ('IELTS_7_PLUS', 'IELTS Band 7+'), ('ESP_FOUNDATION', 'ESP Foundation'), ('ESP_ADVANCED', 'Advanced ESP')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_learning_courses', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='learning.learningprogram')),
            ],
            options={
                'ordering': ['program', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_fa', models.CharField(blank=True, max_length=200)),
                ('module_type', models.CharField(choices=[('VOCABULARY', 'Vocabulary'), ('GRAMMAR', 'Grammar'), ('READING', 'Reading'), ('LISTENING', 'Listening'), ('WRITING', 'Writing'), ('SPEAKING', 'Speaking'), ('PRONUNCIATION', 'Pronunciation'), ('IELTS_SKILL', 'IELTS Skill'), ('ESP_TOPIC', 'Aerospace ESP Topic'), ('REVIEW', 'Review'), ('EXAM', 'Exam')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='learning.learningcourse')),
            ],
            options={
                'ordering': ['course', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LearningItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('item_type', models.CharField(choices=[('WORD', 'Word'), ('PHRASE', 'Phrase'), ('COLLOCATION', 'Collocation'), ('PHRASAL_VERB', 'Phrasal Verb'), ('GRAMMAR_RULE', 'Grammar Rule'), ('COMMON_ERROR', 'Common Error'), ('READING_NOTE', 'Reading Note'), ('LISTENING_NOTE', 'Listening Note'), ('WRITING_PATTERN', 'Writing Pattern'), ('SPEAKING_PATTERN', 'Speaking Pattern'), ('TECHNICAL_TERM', 'Technical Term'), ('OTHER', 'Other')], max_length=30)),
                ('meaning_fa', models.TextField(blank=True)),
                ('definition_en', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('example', models.TextField(blank=True)),
                ('common_mistake', models.TextField(blank=True)),
                ('correct_form', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('PERSONAL', 'Personal Study'), ('TEACHER', 'Teacher'), ('BOOK', 'Book'), ('COURSE', 'Course'), ('ARTICLE', 'Article'), ('WEBSITE', 'Website'), ('AI_ASSISTED', 'AI Assisted'), ('OTHER', 'Other')], default='PERSONAL', max_length=30)),
                ('source_reference', models.CharField(blank=True, max_length=500)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_items', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='learning.coursemodule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearnerError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('VOCABULARY', 'Vocabulary'), ('COLLOCATION', 'Collocation'), ('GRAMMAR', 'Grammar'), ('PREPOSITION', 'Preposition'), ('ARTICLE', 'Article'), ('WORD_FORM', 'Word Formation'), ('SPELLING', 'Spelling'), ('READING', 'Reading'), ('LISTENING', 'Listening'), ('WRITING', 'Writing'), ('SPEAKING', 'Speaking'), ('TECHNICAL_TERM', 'Technical Terminology'), ('TECHNICAL_READING', 'Technical Reading'), ('OTHER', 'Other')], max_length=30)),
                ('student_response', models.TextField(blank=True)),
                ('expected_response', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('is_general_english_error', models.BooleanField(default=False)),
                ('is_esp_specific_error', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learner_errors', to='assessment.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_errors', to=settings.AUTH_USER_MODEL)),
                ('learning_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learner_errors', to='learning.learningitem')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningItemQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learning_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_links', to='learning.learningitem')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_item_links', to='assessment.question')),
            ],
        ),
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('LEARNING', 'Learning'), ('REVIEW', 'Review'), ('MASTERED', 'Mastered')], default='NEW', max_length=20)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('incorrect_count', models.PositiveIntegerField(default=0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('mastery_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learning_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='learning.learningitem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('PAUSED', 'Paused')], default='ACTIVE', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_enrollments', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='learning.learningcourse')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'course'), name='uq_learning_enrollment')],
            },
        ),
        migrations.AddConstraint(
            model_name='coursemodule',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='uq_course_module_order'),
        ),
        migrations.AddIndex(
            model_name='learningitem',
            index=models.Index(fields=['module', 'item_type'], name='learning_item_type_idx'),
        ),
        migrations.AddIndex(
            model_name='learningitem',
            index=models.Index(fields=['created_by', 'created_at'], name='learning_item_user_idx'),
        ),
        migrations.AddIndex(
            model_name='learnererror',
            index=models.Index(fields=['student', 'category'], name='learner_error_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='learnererror',
            index=models.Index(fields=['is_general_english_error', 'is_esp_specific_error'], name='learner_error_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='learningitemquestion',
            constraint=models.UniqueConstraint(fields=('learning_item', 'question'), name='uq_learning_item_question'),
        ),
        migrations.AddConstraint(
            model_name='learningcourse',
            constraint=models.UniqueConstraint(fields=('program', 'title'), name='uq_learning_course_program_title'),
        ),
        migrations.AddIndex(
            model_name='learningprogress',
            index=models.Index(fields=['student', 'next_review_at'], name='learning_review_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='learningprogress',
            constraint=models.UniqueConstraint(fields=('student', 'learning_item'), name='uq_learning_progress'),
        ),
    ]
