# Generated by Django 6.1 on 2026-08-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='assigned_level',
            field=models.CharField(blank=True, choices=[('BEGINNER', 'Beginner'), ('ELEMENTARY', 'Elementary'), ('PRE_INTERMEDIATE', 'Pre-Intermediate'), ('INTERMEDIATE', 'Intermediate'), ('UPPER_INTERMEDIATE', 'Upper-Intermediate'), ('ADVANCED', 'Advanced'), ('IELTS_5', 'IELTS Band 5'), ('IELTS_55', 'IELTS Band 5.5'), ('IELTS_6', 'IELTS Band 6'), ('IELTS_65', 'IELTS Band 6.5'), ('IELTS_7_PLUS', 'IELTS Band 7+'), ('ESP_FOUNDATION', 'ESP Foundation'), ('ESP_ADVANCED', 'Advanced ESP')], max_length=30),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='class_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='placement_status',
            field=models.CharField(choices=[('NOT_ASSESSED', 'Not Assessed'), ('PLACEMENT_TEST', 'Placement Test'), ('TEACHER_ASSIGNED', 'Teacher Assigned')], default='NOT_ASSESSED', max_length=30),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='placement_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
