# Generated by Django 6.1 on 2026-08-20 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_question_track_alter_question_aerospace_domain_and_more'),
        ('learning', '0002_enrollment_assigned_level_enrollment_class_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningitem',
            name='aerospace_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='learning_items', to='assessment.aerospacedomain'),
        ),
        migrations.AddField(
            model_name='learningitem',
            name='aerospace_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='learning_items', to='assessment.aerospacetopic'),
        ),
    ]
