# Generated by Django 6.1 on 2026-08-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_coursemodule_aerospace_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningitem',
            name='english_focus',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='learningitem',
            name='english_topic',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
