# Generated by Django 6.1 on 2026-08-20 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_learningitem_english_focus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20)),
                ('vocabulary_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('grammar_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('reading_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('listening_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overall_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cefr_level', models.CharField(blank=True, default='', max_length=10)),
                ('ielts_estimate', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_attempts', to='learning.learningprogram')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['student', 'program', 'status'], name='placement_student_idx')],
            },
        ),
    ]
