# Generated by Django 6.1 on 2026-08-20 13:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_question_track_alter_question_aerospace_domain_and_more'),
        ('learning', '0006_placementattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_questions', to='learning.learningprogram')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placement_questions', to='assessment.question')),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['program', 'is_active', 'order'], name='placement_pool_idx')],
                'constraints': [models.UniqueConstraint(fields=('program', 'question'), name='uq_placement_question')],
            },
        ),
        migrations.CreateModel(
            name='PlacementResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(max_length=1)),
                ('correct_answer_snapshot', models.CharField(max_length=1)),
                ('skill_snapshot', models.CharField(blank=True, default='', max_length=30)),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='learning.placementattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placement_responses', to='assessment.question')),
            ],
            options={
                'indexes': [models.Index(fields=['attempt', 'skill_snapshot'], name='placement_resp_idx')],
                'constraints': [models.UniqueConstraint(fields=('attempt', 'question'), name='uq_placement_response')],
            },
        ),
    ]
