# Generated by Django 6.1 on 2026-08-20 19:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_question_track_alter_question_aerospace_domain_and_more'),
        ('learning', '0007_placementquestion_placementresponse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PRACTICE_ANSWER', 'Practice Answer'), ('PLACEMENT_COMPLETE', 'Placement Completed'), ('ERROR_RESOLVED', 'Error Resolved')], max_length=40)),
                ('program_type', models.CharField(blank=True, default='', max_length=30)),
                ('skill', models.CharField(blank=True, default='', max_length=30)),
                ('aerospace_domain', models.CharField(blank=True, default='', max_length=200)),
                ('aerospace_topic', models.CharField(blank=True, default='', max_length=200)),
                ('english_focus', models.CharField(blank=True, default='', max_length=100)),
                ('english_topic', models.CharField(blank=True, default='', max_length=100)),
                ('selected_answer', models.CharField(blank=True, default='', max_length=10)),
                ('correct_answer', models.CharField(blank=True, default='', max_length=10)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('mastery_before', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mastery_after', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('review_count_before', models.PositiveIntegerField(blank=True, null=True)),
                ('review_count_after', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learning_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_events', to='learning.learningitem')),
                ('placement_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_events', to='learning.placementattempt')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_events', to='assessment.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['student', 'occurred_at'], name='learn_event_student_idx'), models.Index(fields=['event_type', 'occurred_at'], name='learn_event_type_idx'), models.Index(fields=['program_type', 'skill'], name='learn_event_skill_idx')],
            },
        ),
    ]
