# Generated by Django 6.1 on 2026-08-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('ENGLISH', 'English Learning'), ('IELTS', 'IELTS'), ('AEROSPACE', 'Aerospace English'), ('AI', 'AI Tools'), ('RESEARCH', 'Research Tools')], max_length=30)),
                ('description', models.TextField()),
                ('website_url', models.URLField(blank=True)),
                ('usage_instruction', models.TextField(blank=True)),
                ('recommended_level', models.CharField(blank=True, max_length=50)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
