# Generated by Django 5.2.17 on 2026-09-08 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_guideresource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningprogress',
            options={'verbose_name': 'learning progress', 'verbose_name_plural': 'learning progress'},
        ),
    ]
